# Generated by Django 4.2.7 on 2024-10-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stagiaire',
            new_name='Mission',
        ),
    ]
