# Generated by Django 4.2.7 on 2024-11-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaine',
            name='desc',
        ),
    ]
