# Generated by Django 4.2.7 on 2024-11-01 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_domaine_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='parent',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
