# Generated by Django 4.2.7 on 2024-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='domaine/'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
