# Generated by Django 4.2.7 on 2024-11-07 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_commandesoja'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandesoja',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandesoja',
            name='quantite',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandesoja',
            name='adress',
            field=models.CharField(max_length=50),
        ),
    ]
